services:
  munin:
    image: amartinr/munin-server
    container_name: munin
    ports:
      - 80:80
    volumes:
      - munin:/var/lib/munin
    restart: unless-stopped
    hostname: "munin"

volumes:
  munin:
